# Generated by Django 6.0.2 on 2026-03-01 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatPais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_iso', models.CharField(max_length=2, unique=True)),
                ('emoji_bandera', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_pais',
            },
        ),
        migrations.CreateModel(
            name='CatPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('clase', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('stat_fuerza', models.SmallIntegerField()),
                ('stat_velocidad', models.SmallIntegerField()),
                ('stat_magia', models.SmallIntegerField()),
                ('stat_defensa', models.SmallIntegerField()),
                ('hp_base', models.SmallIntegerField(default=250)),
                ('energia_base', models.SmallIntegerField(default=100)),
                ('companero', models.CharField(blank=True, max_length=100)),
                ('sprite_key', models.CharField(blank=True, max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_personaje',
            },
        ),
        migrations.CreateModel(
            name='CatRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'cat_rol',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('nombre_mostrar', models.CharField(blank=True, max_length=80)),
                ('biografia', models.TextField(blank=True)),
                ('xp_total', models.IntegerField(default=0)),
                ('nivel_cuenta', models.SmallIntegerField(default=1)),
                ('partidas_jugadas', models.IntegerField(default=0)),
                ('partidas_ganadas', models.IntegerField(default=0)),
                ('estrellas_totales', models.IntegerField(default=0)),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('esta_baneado', models.BooleanField(default=False)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.catpais')),
                ('id_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.catrol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumen_general', models.SmallIntegerField(default=80)),
                ('dificultad_default', models.CharField(default='NORMAL', max_length=20)),
                ('perfil_visible', models.CharField(default='PUBLICO', max_length=20)),
                ('mostrar_en_ranking', models.BooleanField(default=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'configuracion_usuario',
            },
        ),
    ]
