# Generated by Django 6.0.2 on 2026-03-07 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_usuario_personaje_seleccionado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_id', models.SmallIntegerField(default=1)),
                ('resultado', models.CharField(choices=[('VICTORIA', 'Victoria'), ('DERROTA', 'Derrota')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('xp_ganada', models.IntegerField(default=0)),
                ('tiempo_segundos', models.IntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('id_personaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.catpersonaje')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'partida',
                'ordering': ['-fecha'],
            },
        ),
    ]
