# Generated by Django 6.0.2 on 2026-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_partida'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_maximo_desbloqueado',
            field=models.SmallIntegerField(default=1),
        ),
    ]
