# Generated by Django 6.0.2 on 2026-03-08 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_usuario_nivel_maximo_desbloqueado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('icono', models.CharField(default='🏅', max_length=10)),
                ('xp_recompensa', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'logro',
            },
        ),
        migrations.CreateModel(
            name='LogroUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_obtenido', models.DateTimeField(auto_now_add=True)),
                ('id_logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.logro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logro_usuario',
                'unique_together': {('id_usuario', 'id_logro')},
            },
        ),
    ]
